Extend optional sysinfo collection to all the benchmarks
- By default collect-sysinfo collects kernel_config, block, libvirt,
  sos, block and ara if installed and configured. This commit will
  allow users to optionally choose what to collect or ignore the
  collection.

Fixes #660

diff --git a/agent/bench-scripts/pbench-dbench b/agent/bench-scripts/pbench-dbench
--- a/agent/bench-scripts/pbench-dbench
+++ b/agent/bench-scripts/pbench-dbench
@@ -54,6 +54,7 @@ tool_group=default
 tool_label_pattern="dbench-"
 thread_counts=`cat /proc/cpuinfo | grep processor | wc -l`
 client_nodes=""
+sysinfo="default"
 
 function install_dbench {
 	if check_install_rpm $benchmark_rpm $ver; then
@@ -90,7 +91,7 @@ function print_header {
 
 
 # Process options and arguments
-opts=$(getopt -q -o i:c:t:r:m:p:M:S:C: --longoptions "client-node:,client-nodes:,client-label:,tool-label-pattern:,install,start-iteration-num:,config:,threads:,runtime:,samples:,client:,clients:,max-stddev:,max-failures:,postprocess-only:,run-dir:,tool-group:" -n "getopt.sh" -- "$@");
+opts=$(getopt -q -o i:c:t:r:m:p:M:S:C: --longoptions "client-node:,client-nodes:,client-label:,tool-label-pattern:,install,start-iteration-num:,config:,threads:,runtime:,samples:,client:,clients:,max-stddev:,max-failures:,postprocess-only:,run-dir:,tool-group:,sysinfo:" -n "getopt.sh" -- "$@");
 if [ $? -ne 0 ]; then
 	printf -- "$*\n"
 	printf "\n"
@@ -126,6 +127,8 @@ if [ $? -ne 0 ]; then
 	printf    "\t\t                                        prefix.  if you don't want to register your tools with \"dbench-\" as\n"
 	printf    "\t\t                                        part of the label, just use --tool-label-pattern= to tell this script\n"
 	printf    "\t\t                                        the prefix pattern to use for CPU information.\n"
+	printf -- "\t\t             --sysinfo=str,             str= comma seperated values of sysinfo to be collected\n"
+	printf -- "\t\t                                             available: $(pbench-collect-sysinfo --options)\n"
 	exit 1
 fi
 eval set -- "$opts";
@@ -228,6 +231,13 @@ while true; do
 			shift;
 		fi
 		;;
+		--sysinfo)
+		shift;
+		if [ -n "$1" ]; then
+			sysinfo="$1"
+			shift;
+		fi
+		;;
 		*)
 		debug_log "[$script_name]what happened? [$1]"
 		break;
@@ -238,6 +248,13 @@ while true; do
 		;;
 	esac
 done
+pbench-collect-sysinfo --sysinfo=$sysinfo --check
+if [ $? != 0 ]; then
+        printf -- "$*\n\n"
+        printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+        usage
+        exit 1
+fi
 if [[ -z "$benchmark_run_dir" ]]; then
 	# We don't have an explicit run directory, construct one
 	benchmark_fullname="${benchmark}_${config}_${date_suffix}"
@@ -300,7 +317,7 @@ let total_iterations=count
 count=1
 max_key_length=0
 export benchmark config
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
 
 for thread_count in `echo $thread_counts | sed -e s/,/" "/g`; do
@@ -513,6 +530,6 @@ done
 
 printf -- "</pre>\n" >>$benchmark_summary_html_file
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir end
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
 
 rmdir $benchmark_run_dir/.running
diff --git a/agent/bench-scripts/pbench-iozone b/agent/bench-scripts/pbench-iozone
--- a/agent/bench-scripts/pbench-iozone
+++ b/agent/bench-scripts/pbench-iozone
@@ -61,6 +61,7 @@ record_sizes="1,2"
 number_of_runs=10
 iteration=1 
 tool_group=default
+sysinfo="default"
 
 ## Ensure the right version of the benchmark is installed
 
@@ -71,7 +72,7 @@ else
 	exit 1
 fi
 
-opts=$(getopt -q -o C:d:s:r:n: --longoptions "config:,targets:,file_sizes:,record_sizes:,number_of_runs:,tool-group:" -n "getopt.sh" -- "$@");
+opts=$(getopt -q -o C:d:s:r:n: --longoptions "config:,targets:,file_sizes:,record_sizes:,number_of_runs:,tool-group:,sysinfo:" -n "getopt.sh" -- "$@");
 
 if [ $? -ne 0 ]; then
         printf -- "$*\n"
@@ -88,6 +89,8 @@ if [ $? -ne 0 ]; then
 	printf -- "\t\t-n str[,str] --number_of_runs=str[,str]\n"
 	printf "\t\t\tnumber of iozone runs - default is 10 runs\n"
 	printf -- "\t\t--tool-group=str\n"
+	printf -- "\t\t--sysinfo=str, str= comma seperated values of sysinfo to be collected\n"
+	printf -- "\t\t                    available: $(pbench-collect-sysinfo --options)\n"
         exit 1
 fi
 
@@ -124,7 +127,14 @@ while true; do
 			record_sizes="$1"
 			shift;
 		fi
-		;; 
+		;;
+	         --sysinfo)
+		shift;
+		if [ -n "$1" ]; then
+			sysinfo="$1"
+			shift;
+		fi
+		;;	
 
 		-n|--number_of_runs)
 		shift
@@ -156,6 +166,14 @@ done
 
 verify_tool_group $tool_group
 
+pbench-collect-sysinfo --sysinfo=$sysinfo --check
+if [ $? != 0 ]; then
+        printf -- "$*\n\n"
+        printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+        usage
+        exit 1
+fi
+
 benchmark_fullname="${benchmark}_${config}_${date_suffix}"
 export benchmark_run_dir="$pbench_run/${benchmark_fullname}"
 benchmark_iterations="$pbench_tmp/${benchmark_fullname}.iterations"
@@ -163,7 +181,7 @@ benchmark_summary_file="$benchmark_run_dir/$benchmark-summary.txt"
 
 mkdir -p $benchmark_run_dir/.running
 export benchmark config
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
 
 benchmark_results_dir="$benchmark_run_dir/$iteration/reference-result"
@@ -187,7 +205,7 @@ done
 pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
 pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir end
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
 
 rmdir $benchmark_run_dir/.running
 
diff --git a/agent/bench-scripts/pbench-linpack b/agent/bench-scripts/pbench-linpack
--- a/agent/bench-scripts/pbench-linpack
+++ b/agent/bench-scripts/pbench-linpack
@@ -40,9 +40,10 @@ start_iteration_num=1
 orig_cmd="$*"
 tool_group=default
 config=""
+sysinfo="default"
 
 # Process options and arguments
-opts=$(getopt -q -o C: --longoptions "config:,threads:,kvm-host:,tool-group:" -n "getopt.sh" -- "$@");
+opts=$(getopt -q -o C: --longoptions "config:,threads:,kvm-host:,tool-group:,sysinfo:" -n "getopt.sh" -- "$@");
 
 if [ $? -ne 0 ]; then
 	printf -- "$*\n"
@@ -53,6 +54,8 @@ if [ $? -ne 0 ]; then
 	printf -- "\t\t-C str --config=str                         name of the test config\n"   
 	printf -- "\t\t--threads=int[,int]                         number of threads to use (default is num_cpus)\n"
 	printf -- "\t\t--tool-group=str\n"
+	printf -- "\t\t--sysinfo=str,                              str= comma seperated values of sysinfo to be collected\n"
+	printf -- "\t\t                                                 available: $(pbench-collect-sysinfo --options)\n"
 	exit 1
 fi
 eval set -- "$opts";
@@ -87,6 +90,13 @@ while true; do
 			shift;
 		fi
 		;;
+		--sysinfo)
+                shift;
+		if [ -n "$1" ]; then
+			sysinfo="$1"
+			shift;
+		fi
+		;;
 		--)
 		shift;
 		break;
@@ -98,7 +108,13 @@ while true; do
 	esac
 done
 verify_tool_group $tool_group
-
+pbench-collect-sysinfo --sysinfo=$sysinfo --check
+if [ $? != 0 ]; then
+        printf -- "$*\n\n"
+        printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+        usage
+        exit 1
+fi
 ## Ensure the right version of the benchmark is installed
 if check_install_rpm $benchmark_rpm $ver; then
     debug_log "[$script_name]$benchmark_rpm is installed"
@@ -120,7 +136,7 @@ benchmark_results_dir="$benchmark_run_dir/$iteration/reference-result"
 result_file=$benchmark_results_dir/result.txt
 mkdir -p $benchmark_results_dir
 export benchmark config
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
 echo $iteration >> $benchmark_iterations
 ## Run the benchmark and start/stop perf analysis tools
@@ -130,6 +146,6 @@ OMP_NUM_THREADS=$threads ./xlinpack_xeon64 < ./linpack.dat | tee $result_file
 pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
 pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir end
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
 
 rmdir $benchmark_run_dir/.running
diff --git a/agent/bench-scripts/pbench-migrate b/agent/bench-scripts/pbench-migrate
--- a/agent/bench-scripts/pbench-migrate
+++ b/agent/bench-scripts/pbench-migrate
@@ -53,9 +53,10 @@ seconds_before_postprocess=1
 use_libvirt="y"
 tool_group=default
 config=""
+sysinfo="default"
 
 # Process options and arguments
-opts=$(getopt -q -o C:c:r:d: --longoptions "max-downtime:,compcache_size:,speed:,seconds-before-postprocess:,seconds-before-migrate:,postprocess:,round-trips:,vm:,dir:,config:,src-host:,src-ipaddr:,dest-host:,dest-ipaddr:,timeout:,use-libvirt:,tool-group:" -n "getopt.sh" -- "$@");
+opts=$(getopt -q -o C:c:r:d: --longoptions "max-downtime:,compcache_size:,speed:,seconds-before-postprocess:,seconds-before-migrate:,postprocess:,round-trips:,vm:,dir:,config:,src-host:,src-ipaddr:,dest-host:,dest-ipaddr:,timeout:,use-libvirt:,tool-group:,sysinfo:" -n "getopt.sh" -- "$@");
 
 if [ $? -ne 0 ]; then
 	printf -- "$*\n"
@@ -79,6 +80,8 @@ if [ $? -ne 0 ]; then
 	printf -- "\t\t--use-libvirt=y/n                       iif this is "n", then migration is done with qemu directly\n"
 	printf -- "\t\t                                        0 = 1 migration, just to dest-host (no round-trip migration, VM ends up on dest-host).\n"
 	printf -- "\t\t                                        1 = 2 migrations, 2 = 4 migrations, etc.  VM ends up on src-host\n"
+	printf -- "\t\t--sysinfo=str,                          str= comma seperated values of sysinfo to be collected\n"
+        printf -- "\t\t                                             available: $(pbench-collect-sysinfo --options)\n"
 	exit 1
 fi
 eval set -- "$opts";
@@ -125,6 +128,13 @@ while true; do
 		shift;
 		if [ -n "$1" ]; then
 			seconds_before_migrate="$1"
+			shift;
+		fi
+		;;
+		--sysinfo)
+		shift;
+		if [ -n "$1" ]; then
+			sysinfo="$1"
 			shift;
 		fi
 		;;
@@ -209,6 +219,14 @@ while true; do
 	esac
 done
 verify_tool_group $tool_group
+
+pbench-collect-sysinfo --sysinfo=$sysinfo --check
+if [ $? != 0 ]; then
+        printf -- "$*\n\n"
+        printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+        usage
+        exit 1
+fi
 
 function do_migrate() {
 
@@ -330,7 +348,7 @@ if [ $loops -eq 0 ]; then
 fi
 count=1
 export benchmark config
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
 for i in `seq 1 $loops`; do
 	iteration="$count-from-$src_host-to-$dest_host"
@@ -374,6 +392,6 @@ for postprocess_dir in $postprocess_dirs; do
 done
 wait
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir end
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
 
 rmdir $benchmark_run_dir/.running
diff --git a/agent/bench-scripts/pbench-netperf b/agent/bench-scripts/pbench-netperf
--- a/agent/bench-scripts/pbench-netperf
+++ b/agent/bench-scripts/pbench-netperf
@@ -75,7 +75,7 @@ start_iteration_num=1
 keep_failed_tool_data="y"
 orig_cmd="$*"
 tool_group=default
-
+sysinfo="default"
 
 function gen_cmd {
 
@@ -141,7 +141,7 @@ function print_header {
 }
 
 # Process options and arguments
-opts=$(getopt -q -o i:c:t:r:m:p:M:S:C: --longoptions "client-label:,server-label:,install,start-iteration-num:,config:,instances:,test-types:,runtime:,message-sizes:,protocols:,samples:,client:,clients:,servers:,server:,max-stddev:,max-failures:,kvm-host:,log-response-times:,postprocess-only:,run-dir:,tool-group:" -n "getopt.sh" -- "$@");
+opts=$(getopt -q -o i:c:t:r:m:p:M:S:C: --longoptions "client-label:,server-label:,install,start-iteration-num:,config:,instances:,test-types:,runtime:,message-sizes:,protocols:,samples:,client:,clients:,servers:,server:,max-stddev:,max-failures:,kvm-host:,log-response-times:,postprocess-only:,run-dir:,tool-group:,sysinfo:" -n "getopt.sh" -- "$@");
 if [ $? -ne 0 ]; then
 	printf -- "$*\n"
 	printf "\n"
@@ -324,6 +324,13 @@ while true; do
 			shift;
 		fi
 		;;
+		--sysinfo)
+		shift;
+		if [ -n "$1" ]; then
+			sysinfo="$1"
+			shift;
+		fi
+		;;
 		*)
 		debug_log "[$script_name]what happened? [$1]"
 		break;
@@ -335,7 +342,13 @@ while true; do
 	esac
 done
 verify_tool_group $tool_group
-
+pbench-collect-sysinfo --sysinfo=$sysinfo --check
+if [ $? != 0 ]; then
+        printf -- "$*\n\n"
+        printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+        usage
+        exit 1
+fi
 if [[ -z "$benchmark_run_dir" ]]; then
         # We don't have an explicit run directory, construct one
         benchmark_fullname="${benchmark}_${config}_${date_suffix}"
@@ -418,7 +431,7 @@ count=1
 # disable firewall on local system
 systemctl stop firewalld
 export benchmark config
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
 # start the server processes
 for protocol in `echo $protocols | sed -e s/,/" "/g`; do
@@ -603,7 +616,7 @@ for protocol in `echo $protocols | sed -e s/,/" "/g`; do
 done
 printf -- "</pre>\n" >>$benchmark_summary_html_file
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir end
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
 
 
 rmdir $benchmark_run_dir/.running
diff --git a/agent/bench-scripts/pbench-specjbb2005 b/agent/bench-scripts/pbench-specjbb2005
--- a/agent/bench-scripts/pbench-specjbb2005
+++ b/agent/bench-scripts/pbench-specjbb2005
@@ -45,9 +45,10 @@ nr_cpus=`cat /proc/cpuinfo | grep processor | wc -l`
 classpath=/usr/local/share/specjbb2005
 tool_group=default
 config=""
+sysinfo="default"
 
 # Process options and arguments
-opts=$(getopt -q -o C:c:r:d: --longoptions "dir:,nr-jvms:,heap-size:,java-opts:,start-warehouses:,inc-warehouses:,stop-warehouses:,runtime:,tool-group:" -n "getopt.sh" -- "$@");
+opts=$(getopt -q -o C:c:r:d: --longoptions "dir:,nr-jvms:,heap-size:,java-opts:,start-warehouses:,inc-warehouses:,stop-warehouses:,runtime:,tool-group:,sysinfo:" -n "getopt.sh" -- "$@");
 
 if [ $? -ne 0 ]; then
 	printf -- "$*\n"
@@ -66,6 +67,8 @@ if [ $? -ne 0 ]; then
 	printf -- "\t\t       --runtime=int                        measurement period in seconds (default is $runtime)\n"
 	printf -- "\t\t-d str --dir=str                            directory to run the test\n"
 	printf -- "\t\t       --tool-group=str\n"
+	printf -- "\t\t       --sysinfo=str,                       str= comma seperated values of sysinfo to be collected\n"
+	printf -- "\t\t                                                 available: $(pbench-collect-sysinfo --options)\n"
 	exit 1
 fi
 eval set -- "$opts";
@@ -142,6 +145,13 @@ while true; do
 			shift;
 		fi
 		;;
+		--sysinfo)
+		shift;
+		if [ -n "$1" ]; then
+			sysinfo="$1"
+			shift;
+		fi
+		;;
 		--)
 		shift;
 		break;
@@ -153,6 +163,14 @@ while true; do
 	esac
 done
 verify_tool_group $tool_group
+
+pbench-collect-sysinfo --sysinfo=$sysinfo --check
+if [ $? != 0 ]; then
+        printf -- "$*\n\n"
+        printf "\t${benchmark}: you specified an invalid --sysinfo option (\"$sysinfo\")\n\n"
+        usage
+        exit 1
+fi
 
 if [ "$stop_warehouses" == "default" ]; then
 	stop_warehouses=`echo "$nr_cpus *2 /$nr_jvms" | bc`
@@ -212,7 +230,7 @@ mv index.html SPECjbb.html
 # rename the iterations with warehouse count and then postprocess the tools
 iteration=1
 export benchmark config
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo beg
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir beg
 for i in `seq $start_warehouses $inc_warehouses $stop_warehouses`; do
 	# for each of the test iterations (each test with a specific number of warehouses), copy the raw result data for that iteration in iteraration directory
@@ -224,7 +242,7 @@ for i in `seq $start_warehouses $inc_warehouses $stop_warehouses`; do
 	let iteration=$iteration+1
 done
 pbench-metadata-log --group=$tool_group --dir=$benchmark_run_dir end
-pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir end
+pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir --sysinfo=$sysinfo end
 popd
 
 rmdir $benchmark_run_dir/.running
